# Generated by Django 4.1.13 on 2024-04-16 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SafePick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('photo_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productc',
            name='background_removed_image',
            field=models.CharField(max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name='productc',
            name='pnns_groups_1',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productf',
            name='allergens',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productf',
            name='background_removed_image',
            field=models.CharField(max_length=100000000, null=True),
        ),
    ]
