# Generated by Django 4.1.13 on 2024-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahrr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
