# Generated by Django 4.1.13 on 2024-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahrr', '0002_remove_userprofile_photo_userprofile_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
