# Generated by Django 4.1.13 on 2024-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahrr', '0003_alter_userprofile_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
