# Generated by Django 4.1.13 on 2024-04-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahrr', '0005_remove_userprofile_photo_name_and_more'),
    ]

    operations = [
    ]
