# Generated by Django 4.1.13 on 2024-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahrr', '0006_auto_20240404_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
